[project]
name = "rbldnsd-operator"
version = "1.0.0a2"
requires-python = ">=3.10"

dependencies = [
    "charmlibs-apt>=1,<2",
    "charmlibs-systemd>=1,<2",
    "ops~=3.7",
]

[dependency-groups]
lint = [
    "ruff>=0.16.0",
    "codespell",
    "ty",
    "zizmor>=1.28.0",
]
unit = [
    "coverage[toml]",
    "ops[testing]",
    "pytest",
]
integration = [
    "jubilant>=1.8,<2",
    "pytest",
    "pytest-jubilant>=2.0.1,<3",
]

# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
pythonpath = ["src"]

# Linting tools configuration
[tool.codespell]
skip = "build,lib,venv,icon.svg,.tox,.git,.mypy_cache,.ruff_cache,.coverage"

[tool.ruff]
line-length = 99
extend-exclude = [
    "__pycache__",
    "*.egg_info",
    "lib",
]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "C4",
    "N",
    "D",
    "I",
    "UP",
    "B",
    "RUF",
]
ignore = [
    "D105",
    "D107",
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = ["S101", "S105", "S106", "S108", "PLR2004", "ARG", "SLF001", "N802", "N803", "N806", "D"]


[tool.ty.src]
include = ["src", "tests"]

[tool.ty.environment]
extra-paths = ["src"]
