name: Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions: {}

jobs:
  lint-and-unit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12", "3.14"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - name: Set up tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Run linting
        run: tox -e lint
      - name: Run unit tests
        run: tox -e unit

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - name: Set up tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Install Concierge
        run: sudo snap install --classic concierge
      - name: Prepare for deploying machine charms
        # The machine preset installs Charmcraft (and Juju and LXD) as well.
        run: sudo concierge prepare -p machine
      - name: Pack charm
        run: charmcraft pack
      - name: Run integration tests
        run: tox -e integration
