name: Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions: {}

jobs:
  charm-unit-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - name: Install Charmcraft
        run: sudo snap install charmcraft --classic
      - name: Fetch any charmlibs
        run: charmcraft fetch-libs
      - name: Run linting
        run: uvx tox -e lint
      - name: Run unit tests
        run: uvx tox -e unit
      - name: Run integration tests
        run: uvx tox -e integration
